  const name = prompt("what is your name");

const age  = prompt("what is your age");


// 1. Get the current 4-digit year
const currentYear = new Date().getFullYear();

   

    // 2. Subtract the birth year
const ageDifference = currentYear - birthYear;


console.log("welcome  ", + name + age)



// Write a function called "addNewPizza" which takes a pizza object and add it to the menu without help



